export const elements = {
  time: document.getElementById("time"),
  date: document.getElementById("date"),
  editable: document.getElementById("editable"),
  notepad: document.getElementById("notepad"),
  linkInput: document.getElementById("link-input"),
  linkContainer: document.getElementById("link-container"),
  weather: document.getElementById("weather"),
  youtube: document.getElementById("youtube"),
  videoContainer: document.getElementById("video-container"),
  setWallpaperBtn: document.getElementById("setWallpaperBtn"),
  addLinkBtn: document.getElementById("add-link-btn"),
  techVideoBtn: document.getElementById("tech-video-btn"),
  resetBtn: document.getElementById("resetBtn"),
  applyApiKeysBtn: document.getElementById("applyApiKeysBtn"),
};
